apiVersion: v1
kind: Pod
metadata: 
  name: mysql
spec:
  containers:  
    - name: db
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysec1
              key: mysqlpassword

