apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata: 
 name: rollingupdate
spec: 
 replicas: 4
 selector:
  matchLabels: 
   app: gopi
 strategy: 
  type: RollingUpdate
  rollingupdate:
   maxsurge: 0
   maxunavailable: 1
   revisionHistoryLimit: 10
 template:
  metadata: 
   labels:
    app: gopi
  spec: 
   containers:
    - name: contain
      image: nginx:1.14
      ports:
        - containerPort: 80
      readinessProbe:
       initialDelaySeconds: 10
       periodSeconds: 1
         
