---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-frontend-svc
spec:
  type: NodePort
  ports:
    - name: web-port
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-backend-svc
  namespace: wordpress
spec:
  type: ClusterIP
  ports:
    - name: db-port
      port: 3306
      targetPort: 3306
  selector:
    app: backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  dbname: wordpress
  dbuser: root
  dbhost: wordpress-backend-svc
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-password: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: wordpress-con
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: dbhost
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: dbuser
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: dbname
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mysql-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: mysql-con
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mysql-password
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
          args: ["--default-authentication-plugin=mysql_native_password"]
      volumes:
        - name: mysql-volume
          emptyDir: {}

